# Generated by Django 3.2 on 2022-05-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20220515_1856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='productspecification',
            options={'verbose_name': 'Especifiación de producto', 'verbose_name_plural': 'Especifiaciónes de producto'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Tipo producto', 'verbose_name_plural': 'Tipos de producto'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Requerido y debe ser único', max_length=255, unique=True, verbose_name='Nombre categoría'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL de categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='No Requerido', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(error_messages={'name': {'max_length': 'El precio debe ser mayor que 0.'}}, help_text='Precio de venta de un elemento', verbose_name='Precio con descuento'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Cambie la visibilidad del producto', verbose_name='Visibilidad del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.PositiveIntegerField(error_messages={'name': {'max_length': 'El precio debe ser mayor que 0.'}}, help_text='Precio de venta de un elemento', verbose_name='Precio normal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Requerido', max_length=255, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='name',
            field=models.CharField(help_text='Required', max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(help_text='Requerido', max_length=255, unique=True, verbose_name='Nombre producto'),
        ),
    ]
