# Generated by Django 3.2 on 2022-05-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20220515_2009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Imagen del producto', 'verbose_name_plural': 'Imágenes del producto'},
        ),
        migrations.AlterModelOptions(
            name='productspecification',
            options={'verbose_name': 'Especificación del producto', 'verbose_name_plural': 'Especificaciones del producto'},
        ),
        migrations.AlterModelOptions(
            name='productspecificationvalue',
            options={'verbose_name': 'Especificación del producto', 'verbose_name_plural': 'Especificaciones del producto'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Tipo de producto', 'verbose_name_plural': 'Tipos de producto'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Required and unique', max_length=255, unique=True, verbose_name='Nombre de la categoría'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL de la categoría'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='No requerido', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_price',
            field=models.PositiveIntegerField(error_messages={'name': {'max_length': 'El precio normal debe ser mayor a 0'}}, help_text='Descuento por ítem', verbose_name='Discount price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Publicado o no publicado', verbose_name='Visibilidad del producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='regular_price',
            field=models.PositiveIntegerField(error_messages={'name': {'max_length': 'El precio normal debe ser mayor a 0'}}, help_text='Valor por ítem', verbose_name='Precio normal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(help_text='Requerido', max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Porfavor ingrese un texto alternativo', max_length=255, null=True, verbose_name='Texto alternativo'),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='name',
            field=models.CharField(help_text='Requerido', max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(help_text='Requerido', max_length=255, unique=True, verbose_name='Nombre producto'),
        ),
    ]
