# Generated by Django 3.2 on 2022-05-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendedor',
            field=models.CharField(default='', help_text='Requerido', max_length=50, verbose_name='Nombre vendedor'),
        ),
    ]
